services:
  app:
    container_name: gitflow-app
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=gitflow.groupmecwide.lan
      - VIRTUAL_PORT=3000
    networks:
      - reverse-proxy
    dns:
      - 192.168.20.10

networks:
  reverse-proxy:
    external: true